FROM node:alpine as build

USER node

WORKDIR /home/node

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /home/node/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]