name: End-to-end tests
on: push

env:
  APP_HOST: $.env.APP_HOST
  APP_PORT: $.env.APP_PORT
  DB_HOST: $.env.DB_HOST
  DB_NAME: $.env.DB_NAME
  DB_PASSWORD: $.env.DB_PASSWORD
  DB_PORT: $.env.DBPORT
  DB_USER: $.env.DB_USER
  FRONTEND_URL: $.env.FRONTEND_URL
  VITE_BACKEND_URL: $.env.URL_BACKEND
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm i
          npm i cross-env
          cd backend
          npm i
          cd ..
          cd frontend
          npm i
          cd ..
          npm run dev-front
          npm run dev-back
          cd frontend
          npm run cy:run
