name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          cd frontend
          npm i

      - name: Run Cypress tests
        run:
          npm run cypress:run
          
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
          
